### PR TITLE
Fix icons not showing and order of precedence for volume_entity

### PR DESCRIPTION
**Pull request by kalhimeo**
Those 2 fixes are included in my branch. Hopefully the owner can merge them in the main branch, otherwise just go and use my fork :p
Fix https://github.com/sbryfcz/harmony-card/issues/64 and https://github.com/sbryfcz/harmony-card/issues/46

### CODE REVIEW

**Comment by Krocko** [comment]
@kalhimeo i can't install your fork.
I get the following error in hacs: `Repostitory structure for 1.1 is not compliant`
Could you please fix this?

**Comment by kalhimeo** [comment]
sorry I don't know how you try to include the fork in hacs, i am still new to this. I personally uninstalled the original version of harmony-card in hacs, then put my compiled .js file in /config/www folder (find the file here https://github.com/kalhimeo/harmony-card/releases/tag/1.1). After that you can add the lovelace ressource manually in HA with "/local/harmony-card.js" as JS module. Once that s done do a full browser refresh with ctrl+F5. Works great here.

**Comment by drinfernoo** [comment]
Can confirm this (at least the icons) are now working with your fork 👍

It even works with `si:` (and I presume `fa...:`) icons, since those integrations have the proper support now as well.

**Comment by stianhoe** [comment]
Works great! Good job!

**Comment by kalhimeo** [comment]
thank you @sbryfcz , will do my best !

**Pull request merged**
