### PR TITLE
Added KeyPad / NumPad

### PR DESCRIPTION
**Pull request by ItzYanick**
Just a simple keypad add like discussed in #19 
Maybe later on we can add a mode to add custom layouts in the config but for now this does the trick until it is finished

### CODE REVIEW

**Review by sbryfcz — COMMENTED** [review]
I like it a lot. Looks great. Clean solution. 

My only comment/question. Do you think hide_keypad should be true by default so that existing users don't suddenly have a keypad appear? Very minor but it seems like that could frustrate some users.

I'll be curious about how the community reacts to the placement of the keypad above the other controls. Guessing more configuration someday might be nice. 

Overall, I like it and am ready to merge, bump, and release if you or someone else could weigh in on the hide_keypad default comment above.

**Comment by ItzYanick** [comment]
Sure I can do that no problem :D
Yea when I get time I would like to make it more configurable and customizable but for now it's just a quick add cause i really wanted to have that one! haha

**Comment by ItzYanick** [comment]
okay just did it real quick (hopfully it works tho havn't tested it haha)

**Comment by ItzYanick** [comment]
okay tested it and it works just fine! You can merge now if you like :D

**Comment by sbryfcz** [comment]
Works great for me. Nice job. Thanks!

**Comment by scooper1** [comment]
just got updated versions
put in the 0 -9 button definitions
but buttons do not show up
any ideas?

------ Original Message ------

**Pull request merged**
