### PR TITLE
Feature: activity icon button & hide activities

### LINKED ISSUE #18: Hide Buttons option when no Activity Selected. And Activity Icons.
Hi. Love your card. 

if you can implement option to hide buttons when no activity is selected and Activity Icon insted of name option that would be reeealy sweet. 

ill watch the progress of your card with high hopes.

### LINKED ISSUE #37: Extra options for activities: icon
It would be nice to replace  the activity text with an icon. Perhaps just by adding a new optional property to activities.

### LINKED ISSUE #44: Optional: Hide activities
I would appreciate an option to hide the Activity buttons. This way it could be possible to embed the device buttons into another layouts.
buttons

### PR DESCRIPTION
**Pull request by mattieha**
This PR will add a new feature to show the activity buttons as icon buttons and a feature to hide activities.

### Activity icon buttons
In the root options there is an option `show_activities_icons` added, when set to true it will use icons on all activity buttons
In the `Activity Options` there is a an option `icon` added, where you define the icon for hte activity.

image

### Hide activities
In the root options there is an option `hide_activities` added, when set to true it will hide the activities row.

image

Closes #44
Closes #37
Closes #18

### CODE REVIEW

**Comment by mattieha** [comment]
@sbryfcz I know it's bad practice to add 2 features in one PR, but since the "Hide activities" is really minor and much easier to add with changes I made for the "Icon" feature I kinda sneaked it into this PR.
Hope you don't mind.

And thanks again for your work on this card, I use it every day!

**Comment by skank01** [comment]
Thanks !

**Comment by sbryfcz** [comment]
So sorry for the delay! This looks great 👍

**Comment by sbryfcz** [comment]
@mattieha - Let me know if you want to be a contributor. I, unfortunately, don't have the time I would like to dedicate to this.

**Comment by mattieha** [comment]
@sbryfcz Yes i would like to be contibutor, I have another PR in the making.

**Pull request merged**
