### PR TITLE
fix buttons in home assistant 0.110.1

### LINKED ISSUE #25: Icons missing
After updating to .110b0 all my icons are missing

### PR DESCRIPTION
**Pull request by MichaelBitard**
Resolves #25 and probably #24

This fix is related to this PR: https://github.com/home-assistant/frontend/pull/4379 which was merged in home assistant

### CODE REVIEW

**Comment by ronniebee** [comment]
Euhh well I'm trying to figure out how to replace the 11 paper buttons. I found the JS file but how to edit? Can you help this newbee?

**Comment by sbryfcz** [comment]
Thanks for the PR!

**Comment by MichaelBitard** [comment]
You're welcome!

@ronniebee you can edit the file as a text file.

you don't know where it is located or how to edit a text file?

**Comment by ronniebee** [comment]
Found  it, was looking in the wrong place.. it's in my www directory..

**Pull request merged**
